import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="text-gray-400 bg-gray-900 body-font">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
            <Image
              src="https://next-auth.js.org/img/logo/logo-sm.png"
              width={30}
              height={30}
              alt="Logo"
            ></Image>
            <span className="ml-3 text-xl">Next Auth</span>
          </a>
          <nav className="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-700	flex flex-wrap items-center text-base justify-center">
            <Link href="/">
              <a className="mr-5 hover:text-white">Home</a>
            </Link>
            <Link href="/about">
              <a className="mr-5 hover:text-white">About</a>
            </Link>
            <Link href="/services">
              <a className="mr-5 hover:text-white">Services</a>
            </Link>
            <Link href="/contact">
              <a className="mr-5 hover:text-white">Contact</a>
            </Link>
          </nav>

          {session ? (
            //Render if there's already a session
            <div className="flex items-center gap-5">
              <Image
                className="rounded-full"
                width={50}
                height={50}
                alt="user"
                src={session.user?.image as string}
              ></Image>
              <div className="">
                <p className="text-md"> {session.user?.name} </p>
                <p className="text-sm"> {session.user?.email} </p>
              </div>
              <button
                onClick={() => signOut()}
                className="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0"
              >
                Sign Out
                <svg
                  fill="none"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  className="w-4 h-4 ml-1"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </button>
            </div>
          ) : (
            //Render if there's no session
            <a
              href={`/api/auth/signin`}
              onClick={(e) => {
                e.preventDefault();
                signIn();
              }}
            >
              Sign in
            </a>
          )}
        </div>
      </header>
    </div>
  );
};

export default Home;
